<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-04T07:29:28 IST" name="SauceTestSuite" finished-at="2021-11-04T07:29:50 IST" duration-ms="22028">
    <groups>
    </groups>
    <test started-at="2021-11-04T07:29:28 IST" name="SauceTestCases" finished-at="2021-11-04T07:29:50 IST" duration-ms="22028">
      <class name="com.sauce.testcases.PlaceOrder">
        <test-method signature="placeOrder()[pri:0, instance:com.sauce.testcases.PlaceOrder@34f7cfd9]" started-at="2021-11-04T07:29:28 IST" name="placeOrder" finished-at="2021-11-04T07:29:40 IST" duration-ms="12233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
      </class> <!-- com.sauce.testcases.PlaceOrder -->
      <class name="com.sauce.testcases.LoginTest">
        <test-method signature="logintest()[pri:0, instance:com.sauce.testcases.LoginTest@1ba9117e]" started-at="2021-11-04T07:29:40 IST" name="logintest" finished-at="2021-11-04T07:29:44 IST" duration-ms="3194" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PRODUCT] but found [PRODUCTS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PRODUCT] but found [PRODUCTS]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.sauce.testcases.LoginTest.logintest(LoginTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
      </class> <!-- com.sauce.testcases.LoginTest -->
      <class name="com.sauce.testcases.LogoutTest">
        <test-method signature="logout()[pri:0, instance:com.sauce.testcases.LogoutTest@732c2a62]" started-at="2021-11-04T07:29:44 IST" name="logout" finished-at="2021-11-04T07:29:50 IST" duration-ms="6543" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.sauce.testcases.LogoutTest -->
    </test> <!-- SauceTestCases -->
  </suite> <!-- SauceTestSuite -->
</testng-results>
